// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPcr4P9LZZ9oJgT9P9tmDfKRJaHKbRSRI',
    appId: '1:48373505577:web:0e407f86c8023886c24638',
    messagingSenderId: '48373505577',
    projectId: 'translation-app-de645',
    authDomain: 'translation-app-de645.firebaseapp.com',
    storageBucket: 'translation-app-de645.appspot.com',
    measurementId: 'G-8CP0640WRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChb5Vf_tOVyRpxLUcNinayegTdXOqZcvQ',
    appId: '1:48373505577:android:f81f62b8eb6fc719c24638',
    messagingSenderId: '48373505577',
    projectId: 'translation-app-de645',
    storageBucket: 'translation-app-de645.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG5k1IIzvuCnqkfpq1giQPyq-2QWfZrUM',
    appId: '1:48373505577:ios:d98339f6f9be6e69c24638',
    messagingSenderId: '48373505577',
    projectId: 'translation-app-de645',
    storageBucket: 'translation-app-de645.appspot.com',
    iosBundleId: 'com.example.signLanguageTranslator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG5k1IIzvuCnqkfpq1giQPyq-2QWfZrUM',
    appId: '1:48373505577:ios:d98339f6f9be6e69c24638',
    messagingSenderId: '48373505577',
    projectId: 'translation-app-de645',
    storageBucket: 'translation-app-de645.appspot.com',
    iosBundleId: 'com.example.signLanguageTranslator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPcr4P9LZZ9oJgT9P9tmDfKRJaHKbRSRI',
    appId: '1:48373505577:web:67f1b2240edf9e5fc24638',
    messagingSenderId: '48373505577',
    projectId: 'translation-app-de645',
    authDomain: 'translation-app-de645.firebaseapp.com',
    storageBucket: 'translation-app-de645.appspot.com',
    measurementId: 'G-39KC398HVC',
  );
}
